name: Global Workflows Support
description: This action introduces support for global workflows.
inputs:
  github_token:
    description: >
      Token to use GitHub API. It must have "repo" and "workflow" scopes so it can push to repo and edit workflows.
      It cannot be the default GitHub Actions token GITHUB_TOKEN. GitHub Action token's permissions are limited to the repository that contains your workflows.
      Provide token of the user that has rights to push to the repos that this action is suppose to update. 
    required: true
  committer_username:
    description: >
      The username (not display name) of the committer that will be used in the commit of changes in the workflow file in specific repository.
      In the format `web-flow`.
    default: web-flow
    required: false
  committer_email:
    description: >
      The email of the committer that will be used in the commit of changes in the workflow file in specific repository.
      In the format `noreply@github.com`.
    default: noreply@github.com
    required: false
  commit_message:
    description: >
      It is used as a commit message when pushing changes with global workflows. 
      It is also used as a title of the pull request that is created by this action.
    default: Update global workflows
    required: false
  files_to_ignore:
    description: >
      Comma-separated list of workflow files that should be ignored by this action and not updated in other repositories.
      You must provide here at least the name of the workflow file that uses this action.
      In the format `file.yml,another_file.yml`.
    required: true
  repos_to_ignore:
    description: >
      Comma-separated list of repositories that should not get updates from this action.
      Action already ignores the repo in which the action is triggered so you do not need to add it explicitly.
      In the format `repo1,repo2`.
    required: false
  topics_to_include:
    description: >
      Comma-separated list of topics that should get updates from this action. 
      Repos that do not contain one of the specified topics will get appended to the repos_to_ignore list. 
      In the format topic1,topic2.
    required: false
  exclude_archived:
    description: >
      Boolean value on whether to exclude arcived repositories from this action.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: compass
  color: gray-dark
